# Generated by Django 3.0.4 on 2020-04-14 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='match_scopa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_to_play', models.IntegerField(default=1)),
                ('players_amount', models.IntegerField(default=2)),
                ('player1_hand', models.TextField(max_length=22, null=True)),
                ('player2_hand', models.TextField(max_length=22, null=True)),
                ('player3_hand', models.TextField(max_length=22, null=True)),
                ('player4_hand', models.TextField(max_length=22, null=True)),
                ('player1_points', models.IntegerField(default=0, null=True)),
                ('player2_points', models.IntegerField(default=0, null=True)),
                ('player3_points', models.IntegerField(null=True)),
                ('player4_points', models.IntegerField(null=True)),
                ('player1_takes', models.TextField(max_length=81, null=True)),
                ('player2_takes', models.TextField(max_length=81, null=True)),
                ('player3_takes', models.TextField(max_length=81, null=True)),
                ('player4_takes', models.TextField(max_length=81, null=True)),
                ('ground', models.TextField(max_length=22, null=True)),
                ('is_started', models.BooleanField(default=False)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to=settings.AUTH_USER_MODEL)),
                ('player3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_3', to=settings.AUTH_USER_MODEL)),
                ('player4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_4', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='match_invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CardGames.match_scopa')),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='games_notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=300)),
                ('invite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CardGames.match_invitation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
