# Generated by Django 3.0.4 on 2020-04-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardGames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_scopa',
            name='deck',
            field=models.TextField(max_length=82, null=True),
        ),
    ]
