# Generated by Django 2.2.10 on 2020-04-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardGames', '0002_match_scopa_deck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match_scopa',
            old_name='is_started',
            new_name='is_started_game',
        ),
        migrations.AddField(
            model_name='match_scopa',
            name='is_started_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match_scopa',
            name='match_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match_scopa',
            name='player1_scope',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='match_scopa',
            name='player2_scope',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='match_scopa',
            name='player3_scope',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='match_scopa',
            name='player4_scope',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
