# Generated by Django 3.0.3 on 2020-04-16 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CardGames', '0003_auto_20200415_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_scopa',
            name='created_on',
            field=models.DateField(default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AddField(
            model_name='match_scopa',
            name='last_used_on',
            field=models.DateField(default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AlterField(
            model_name='games_notification',
            name='invite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CardGames.match_invitation'),
        ),
        migrations.AlterField(
            model_name='match_scopa',
            name='deck',
            field=models.TextField(blank=True, max_length=82, null=True),
        ),
        migrations.AlterField(
            model_name='match_scopa',
            name='ground',
            field=models.TextField(blank=True, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='match_scopa',
            name='player1_hand',
            field=models.TextField(blank=True, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='match_scopa',
            name='player1_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match_scopa',
            name='player1_scope',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match_scopa',
            name='player1_takes',
            field=models.TextField(blank=True, max_length=81, null=True),
        ),
        migrations.AlterField(
            model_name='match_scopa',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match_scopa',
            name='player2_hand',
            field=models.TextField(blank=True, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='match_scopa',
            name='player2_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match_scopa',
            name='player2_scope',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match_scopa',
            name='player2_takes',
            field=models.TextField(blank=True, max_length=81, null=True),
        ),
        migrations.AlterField(
            model_name='match_scopa',
            name='player3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match_scopa',
            name='player3_hand',
            field=models.TextField(blank=True, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='match_scopa',
            name='player3_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match_scopa',
            name='player3_scope',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match_scopa',
            name='player3_takes',
            field=models.TextField(blank=True, max_length=81, null=True),
        ),
        migrations.AlterField(
            model_name='match_scopa',
            name='player4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match_scopa',
            name='player4_hand',
            field=models.TextField(blank=True, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='match_scopa',
            name='player4_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match_scopa',
            name='player4_scope',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match_scopa',
            name='player4_takes',
            field=models.TextField(blank=True, max_length=81, null=True),
        ),
    ]
