# Generated by Django 3.0.3 on 2020-04-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardGames', '0004_auto_20200416_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='games_notification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
