# Generated by Django 3.0.3 on 2020-04-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardGames', '0005_games_notification_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_scopa',
            name='last_player_to_take',
            field=models.IntegerField(default=0),
        ),
    ]
