# Generated by Django 3.0.3 on 2020-04-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardGames', '0006_match_scopa_last_player_to_take'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_scopa',
            name='last_plays',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
