# Generated by Django 3.0.7 on 2020-06-22 08:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moody', '0002_auto_20200622_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moody_record',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, null=True, size=None),
        ),
    ]
