# Generated by Django 2.2.2 on 2020-02-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budgeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='starting_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(default='', max_length=100, null=True),
        ),
    ]
