# Generated by Django 2.2.10 on 2020-03-27 10:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Budgeting', '0003_auto_20200301_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryexpinc',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 10, 8, 3, 715986, tzinfo=utc), editable=False),
        ),
    ]
