# Generated by Django 3.0.4 on 2020-03-28 10:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Budgeting', '0004_categoryexpinc_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryexpinc',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 10, 54, 33, 298931, tzinfo=utc), editable=False),
        ),
    ]
