# Generated by Django 3.0.4 on 2020-03-28 10:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Budgeting', '0005_auto_20200328_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryexpinc',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 10, 59, 21, 459606, tzinfo=utc), editable=False),
        ),
    ]
