# Generated by Django 3.0.4 on 2020-03-28 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Budgeting', '0006_auto_20200328_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryexpinc',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
