# Generated by Django 3.0.7 on 2020-07-19 20:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Budgeting', '0009_auto_20200430_1843'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('name', 'user_full')},
        ),
        migrations.AlterUniqueTogether(
            name='categoryexpinc',
            unique_together={('name', 'user_full')},
        ),
    ]
