# Generated by Django 3.1.6 on 2021-03-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budgeting', '0012_auto_20210322_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryexpinc',
            name='color',
            field=models.CharField(default='#ff0000', max_length=7),
        ),
    ]
