# Generated by Django 3.0.7 on 2020-07-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
