# Generated by Django 3.0.7 on 2020-07-06 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0002_auto_20200706_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='players',
            field=models.ManyToManyField(related_name='players', through='games.Players_room_m2m', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='players_room_m2m',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_room_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='players_room_m2m',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_room_related', to='games.GameRoom'),
        ),
    ]
