# Generated by Django 3.0.7 on 2020-07-07 07:57

from django.db import migrations, models
import games.database.fields


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200706_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aooo', games.database.fields.CardStackField(max_length=104)),
            ],
        ),
    ]
