# Generated by Django 3.0.7 on 2020-07-07 08:25

import django.contrib.postgres.fields
from django.db import migrations
import games.database.fields


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_db_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_test',
            name='t',
            field=django.contrib.postgres.fields.ArrayField(base_field=games.database.fields.CardStackField(max_length=104), default=None, null=True, size=None),
        ),
    ]
