# Generated by Django 3.0.7 on 2020-07-07 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_db_test_t'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DB_test',
        ),
    ]
