# Generated by Django 3.0.7 on 2020-07-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_delete_db_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='object_id',
        ),
    ]
