# Generated by Django 3.0.7 on 2020-07-20 17:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import games.database.fields


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20200720_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='CactusGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_started', models.BooleanField(default=False)),
                ('match_started', models.BooleanField(default=False)),
                ('public_latest_actions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, default=None, null=True, size=None)),
                ('player_ids', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(default=0), blank=True, null=True, size=None)),
                ('player_cards', django.contrib.postgres.fields.ArrayField(base_field=games.database.fields.CardStackField(max_length=104), blank=True, default=None, null=True, size=None)),
                ('player_points', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, default=None, null=True, size=None)),
                ('player_first_cards', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), blank=True, default=None, null=True, size=None)),
                ('card_drawn', models.CharField(blank=True, default='', max_length=2, null=True)),
                ('player_to_play', models.SmallIntegerField(blank=True, default=-1, null=True)),
                ('last_player_to_play', models.SmallIntegerField(blank=True, default=-1, null=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='GameObject', to='games.GameRoom')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
